### ISSUE TITLE
will you publish test results ?

### ISSUE THREAD

**Issue by mh-cbon** [mafintosh/p2p-test#1]
Hi!

Nice stuff as usual. Whats the intent ? Will you publish test results ? Do you have enough tests ?

On a more technical level, is this test not a bit weak `a.port === b.port && a.host === b.host` to determine HPunch ? I m no specialist, i only read many different papers and it seem to me there was a bit more cases to handle. just wondering.

**Comment by mafintosh** [comment]
OF COURSE I'LL PUBLISH THEM :D. Just updated the README to reflect that, https://github.com/mafintosh/p2p-test#results. The test checks that the external NAT on the network you are testing is using the same port when sending UDP messages to different IPs from the same local socket. If two networks have this property they'll be able to establish a direct p2p connection between them. I'm writing a blog post after this survey that explains this in more detail as well.

**Comment by mh-cbon** [comment]
awesome :) thanks!
